config/routes.rb
Vbook::Application.routes.draw do
  scope '(:locale)' do
    resources :books
    resources :authors
    get 'home/index'
    get 'home/catalog'
    root :to => 'home#index'
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name, :book_ids
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :isbn, :publishing_date, :title, :pages, :cover, :author_ids

  has_and_belongs_to_many :authors

  accepts_nested_attributes_for :authors

  has_attached_file :cover, styles: { medium: '230x230>', edit: '165x165>', thumb: '60x60>' },
                    url: '/uploads/img/books/:id/:style/:basename.:extension',
                    path: ':rails_root/public/uploads/img/books/:id/:style/:basename.:extension',
                    default_url: '/assets/books/default/:style/question-mark.gif'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_i18n_locale_from_params
  protect_from_forgery

  protected
    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.include?(params[:locale].to_sym)
          I18n.locale = params[:locale]
        else
          redirect_to root_url
        end
      end
    end
    def default_url_options
      { locale: I18n.locale }
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.order(:name).paginate(page: params[:page], per_page: 10)
    @page_title = t('titles.authors.index')
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
    @page_title = t('titles.authors.new')
  end

  def edit
    @author = Author.find(params[:id])
    @page_title = @author.name
  end

  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.js { render json: @author }
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
      else
        format.js { render json: { errors: @author.errors } }
        format.html { render action: "new" }
      end
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update_attributes(params[:author])
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_url
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.paginate(page: params[:page], per_page: 10)
    @page_title = t('titles.books.index')
  end

  def show
    @book = Book.find(params[:id])
    @page_title = @book.title
  end

  def new
    @book = Book.new
    @authors = Author.order(:name)
    @page_title = t('titles.books.new')
  end

  def edit
    @book = Book.find(params[:id])
    @authors = Author.order(:name)
    @page_title = @book.title
  end

  def create
    @book = Book.new(params[:book])

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.authors.destroy_all unless params[:book].has_key?('author_ids')

    if @book.update_attributes(params[:book])
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def catalog
    @books = Book.paginate(page: params[:page], per_page: 20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = @page_title ? "#{@page_title} :: #{SITE_NAME}" : SITE_NAME rescue 'SITE_NAME'
    content_tag('title', title, nil, false)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1><%= t('authors.list.header') %></h1>

<%= will_paginate @authors %>

<table class="table table-bordered list">
  <tr>
    <th><%= t('authors.list.name') %></th>
    <th></th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td class="name">
        <strong><%= link_to author.name, edit_author_path(author) %></strong>
      </td>
      <td class="actions">
        <%= link_to t('authors.list.destroy'), author, method: :delete, data: { confirm: 'Are you sure?' },
                    class: 'btn btn-danger btn-small' %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @authors %>

app/views/authors/new.html.erb
<h1>New author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @author.name %>
</p>
<%= link_to 'Edit', edit_author_path(@author) %> |

app/views/books/_form.html.erb
<script type="text/javascript">
  $(document).ready(function()
  {
    $('#new-author').keydown(function(event)
    {
      if(event.which == 13)
      {
        event.preventDefault();
        
        if($(this).val() != '')
        {
          $.ajax({
            url: '<%= authors_url %>',
            type: 'post',
            dataType: 'json',
            data: {
              'author[name]': $(this).val()
            },
            success: function(response)
            {
              if(response.errors)
              {
                  return;
              }

              $('#authors').prepend(
                $('<li>').append(
                  $('<input>').attr({
                    type: 'checkbox',
                    name: 'book[author_ids][]',
                    id: 'author_' + response.id,
                    checked: true
                  }).val(response.id).addClass('author-checkbox')
                ).append(
                  $('<button>').attr({
                    type: 'button'
                  }).addClass('btn btn-mini author active').append(
                    $('<i>').addClass('icon-ok')
                  ).append(
                    $('<span>').text(response.name)
                  )
                )
              )
            }
          });
        }
      }
    });
  });
</script>

<%= form_for @book, html: { multipart: true } do |form| %>
  <div id="cover" class="fileupload fileupload-new pull-left" data-provides="fileupload">
    <div class="fileupload-new thumbnail img-polaroid">
      <%= image_tag @book.cover.url(:edit) %>
    </div>
    <div class="fileupload-preview fileupload-exists thumbnail img-polaroid"></div>
    <div>
      <span class="btn btn-file">
        <span class="fileupload-new">Select image</span>
        <span class="fileupload-exists">Change</span>
        <%= form.file_field :cover %>
      </span>
      <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
    </div>
  </div>
  <div id="title-description" class="pull-left span7">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'span7' %>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'span7' %>
  </div>
  <div id="details" class="pull-left span2">
    <label>Authors:</label>
    <div id="new-author-wrapper" class="input-append">
      <%= text_field_tag 'new-author', nil, autocomplete: 'off' %>
      <span class="add-on"><i id="new-author-help" class="icon-question-sign"></i></span>
    </div>
    <ul id="authors" class="btn-group well unstyled" data-toggle="buttons-checkbox">
        <% @authors.each do |author| %>
          <li>
            <%= check_box_tag 'book[author_ids][]', author.id,
                              @book.author_ids.include?(author.id),
                              id: dom_id(author), class: 'author-checkbox' %>
            <%= button_tag type: 'button', class: 'btn btn-mini author' do %>
                <i class="icon-remove" ></i>
                <span><%= author.name %></span>
            <% end %>
          </li>
        <% end %>
    </ul>
    <%= form.label :publishing_date %>
    <div id="publishing-date-wrapper" class="input-append">
      <%= form.text_field :publishing_date, class: 'input-medium' %>
      <span class="add-on"><i id="publishing-date-icon" class="icon-calendar"></i></span>
    </div>
    <%= form.label :pages %>
    <%= form.text_field :pages, class: 'input-mini' %>
    <%= form.label :isbn %>
    <%= form.text_field :isbn, class: 'input-medium' %>
  </div>
  <ul id="actions" class="inline pull-right">
    <li>
      <%= form.submit @book.new_record? ? t('books.form.label.add') : t('books.form.label.update'),
                      class: 'btn btn-primary' %>
    </li>
    <li>
      <%= link_to 'Cancel', @book, class: 'btn', id: 'cancel' %>
    </li>
  </ul>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1><%= t('books.list.header') %></h1>

<%= will_paginate @books %>

<table class="table table-bordered list">
  <thead>
  <tr>
    <th></th>
    <th><%= t('books.list.title') %></th>
    <th><%= t('books.list.author') %></th>
    <th><%= t('books.list.published') %></th>
    <th><%= t('books.list.description') %></th>
  </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td class="cover">
          <a href="<%= book.cover.url %>" class="fancybox">
            <%= image_tag book.cover.url(:thumb), class: 'img-polaroid' %>
          </a>
        </td>
        <td class="title">
          <strong><%= link_to book.title, book %></strong>
        </td>
        <td class="author">
          <% if book.authors.empty? %>
            -
          <% else %>
            <% book.authors.each do |author| %>
              <%= author.name %><br />
            <% end %>
          <% end %>
        </td>
        <td class="published">
          <%= book.publishing_date %>
        </td>
        <td class="description">
          <%= truncate book.description, length: 160, separator: ' ' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @books %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h4>
  <em>
    <% if @book.authors.empty? %>
      -
    <% else %>
      <%= 'by ' %>
      <% @book.authors.each_with_index do |author, i| %>
        <% author.name.concat(',') unless @book.authors.length - 1 == i %>
        <%= author.name %>
      <% end %>
    <% end %>
  </em>
</h4>
<a href="<%= @book.cover.url %>" class="fancybox">
  <%= image_tag @book.cover.url(:medium), class: 'pull-left img-polaroid' %>
</a>
<p id="description" class="pull-left">
  <%= @book.description %>
</p>
<ul id="details" class="unstyled pull-left">
  <li>
    <strong>Published:</strong> <%= @book.publishing_date %>
  </li>
  <li>
    <strong>Pages:</strong> <%= @book.pages %>
  </li>
  <li>
    <strong>ISBN:</strong> <%= @book.isbn %>
  </li>
</ul>
<ul id="actions" class="inline pull-right">
  <li>
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-info' %>
  </li>
  <li>
    <%= link_to 'Destroy', @book, method: :delete,
                data: { confirm: 'Are you sure? This operation cannot be undone' },
                class: 'btn btn-danger' %>
  </li>
</ul>

app/views/home/catalog.html.erb
<h1><%= t('.title') %></h1>

<%= will_paginate @books %>

<% @books.each do |book| %>
  <div class="row book-row">
    <div class="span12">
      <h3 class="title"><%= book.title %></h3>
      <div class="row">
        <div class="span8">
          <p><%= book.description %></p>
        </div>
        <div class="span4">
          <dl class="dl-horizontal book-details-list">
            <dt><%= t('.pages') %></dt><dd class="pages"><%= book.pages %></dd>
            <dt><%= t('.published') %></dt><dd class="publishing-date"><%= book.publishing_date %></dd>
            <dt><%= t('.isbn') %></dt><dd class="isbn"><%= book.isbn %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= will_paginate @books %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="<%= root_path %>">
      <%= SITE_NAME %>
    </a>
    <%= render_list class: "nav" do |li|
      li << link_to(t("menu.catalog"), { controller: :home, action: :catalog })
    end %>
    <ul class="nav pull-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= t('menu.books.label') %>
          <b class="caret"></b>
        </a>
        <%= render_list class: "dropdown-menu" do |li|
          li << link_to(t('menu.books.show'), books_path)
          li << link_to(t('menu.books.add'), new_book_path)
        end %>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= t('menu.authors.label') %>
          <b class="caret"></b>
        </a>
        <%= render_list class: "dropdown-menu" do |li|
          li << link_to(t('menu.authors.show'), authors_path)
          li << link_to(t('menu.authors.add'), new_author_path)
        end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= page_title %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= render_body_tag %>
  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= notice_message %>
    <%= yield %>
  </div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>